### ISSUE TITLE
topQuery complaints when merging android-support branch with develop

### ISSUE THREAD

**Issue by Adonai** [Fayth/vcmi-android#3]
Let's fix this if we can - I just don't know enough about VCMI yet.

So, I merged your android-support branch with main repo's develop branch and now whenever I get any dialogue in game and click OK server complaints that I have top level query that I have to answer before proceeding.

If you know what this is, I hope to get the build finally functional under GNU/Linux + GCC and -O3, if not, I can provide exact error messages from logcat.

**Comment by Fayth** [comment]
Does it crash the game? I'm quite sure I've seen that error message at some point.

I guess I can check it on my side later today.

**Comment by Adonai** [comment]
No, animation continues, music plays but no controls are working, buttons are not clickable etc. Server supposedly waits for dialogue to be closed and doesn't understand we closed it already.

10 апреля 2017 г. 11:16:33 GMT+03:00, Fay <notifications@github.com> пишет:
>Does it crash the game? I'm quite sure I've seen that error message at
>some point.
>
>I guess I can check it on my side later today.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Fayth/vcmi-android/issues/3#issuecomment-292880435

-- 
Простите за краткость, создано в K-9 Mail.

**Comment by Fayth** [comment]
Okay, so I don't really have any solution for now. The problem is that I don't know vcmi code very well, so it's mostly trial and error.

Have you tried compiling without optimizations?

I can try checking the possible causes if you paste that error message, but honesty I'm not sure I can find a reasonable solution. Maybe it's worth asking on main vcmi forums.

**Comment by Adonai** [comment]
I'll try without optimizations today.
If that fails, I'll bisect the commits between your branch and latest develop to find offending code.

**Comment by Adonai** [comment]
Rebuilding with gnustl_shared solved the issue.

Obscure error it was, really.
